### ISSUE TITLE
Consider supporting precompilation 

### ISSUE THREAD

**Issue by mindreframer** [AlexR2D2/duckdbex#1]
Wow, finally a wrapper for DuckDB! 

There is a discussion about precompiling SQLite for Exqlite, maybe this could be also useful here?  

- https://github.com/elixir-sqlite/exqlite/issues/230

**Comment by AlexR2D2** [comment]
I think so, thanks I'll take a look

**Comment by warmwaffles** [comment]
@mindreframer precompilation was added in https://github.com/elixir-sqlite/exqlite/pull/234

**Comment by mindreframer** [comment]
@warmwaffles Thanks, I'll take a look!

**Comment by warmwaffles** [comment]
The build and release workflow changes a little bit.

1. Drop tag on main branch `v1.2.3`.
2. Wait for the precompilation build to finish.
3. Run `mix elixir_make.checksum --all`.
4. Run `mix hex.publish`

**Comment by AlexR2D2** [comment]
Thanks!

**Comment by AlexR2D2** [comment]
Precompiling for macOS and Linux is ready, v0.2.0, thanks to all! :)
Windows is not precompiled yet, so let's leave the issue open, until i fix the win precompilation in v0.2.1

**Comment by mindreframer** [comment]
@AlexR2D2 Thank you! I've tried it, works like magic! No compilation step, Duckdb immediately usable. Very nice. 

I've noticed, that the embedded Duckdb code is not up-to-date, the DB that was created by Duckdbex is not directly loadable by the latest CLI (0.7.0): 

```bash 
Error: unable to open database "exis_movies.duckdb": IO Error: Trying to read a database file with version number 41, but we can only read version 43.
The database file was created with an older development version of DuckDB.

The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
The storage will be stabilized when version 1.0 releases.
For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.
```

That's actually a PITA, that Duckdb does not provide backwards compatibility yet. Maybe we can provide some inspectable information, like: 

```elixir
iex> Duckdbex.info() 
%{duckdb_verion: "0.6.0"}
```


I've tried to parse this information from Duckdb PRAGMA, but it looks strange: 

```elixir
$ iex -S mix
iex(1)> {:ok, db} = Duckdbex.open("exis_movies.duckdb")
{:ok, #Reference<0.2058083995.1741291542.83541>}
iex(2)> {:ok, conn} = Duckdbex.connection(db)
{:ok, #Reference<0.2058083995.1741291542.83548>}
iex(3)> {:ok, res} = Duckdbex.query(conn, "PRAGMA version;")
{:ok, #Reference<0.2058083995.1741291542.83549>}
iex(4)> Duckdbex.fetch_all(res)
[["v0.1.1-dev436", "2fd5e0d925"]]
iex(5)>
```
Just some basic usability feedback. Maybe it makes sense to create another issue for this.

**Comment by AlexR2D2** [comment]
Yes, [until DuckDB in the development](The DuckDB internal storage format is currently in flux,) the backward compatibility is not supported.

I will try to update DuckDB source up to 0.7.0 and may be add something to get the the version of library and the DB ver itself. So yes, it would be great to create new issues just not to forget about this.

**Comment by mindreframer** [comment]
Done here: https://github.com/AlexR2D2/duckdbex/issues/5

**Comment by mindreframer** [comment]
Closing, since it's implemented.
