### ISSUE TITLE
library_version for duckdbex 0.2.5 is vv0.9.1

### ISSUE THREAD

**Issue by robert-baldwin** [AlexR2D2/duckdbex#12]
Hey there,

Thank you for creating an Elixir client for DuckDB. Hopefully this is helpful information for you.

When I try the newest version, 0.2.5, the `library_version` returns `vv0.9.1` preventing me from installing extensions.

Here's more information on my setup and how the error appeared to me.

# Local Installation
## Livebook code
```
Mix.install([
  {:duckdbex, "~> 0.2.5"}
])
```
```
conf = %Duckdbex.Config{allow_unsigned_extensions: true}
{:ok, db} = Duckdbex.open(conf)
{:ok, conn} = Duckdbex.connection(db)
```
```
{:ok, _} = Duckdbex.query(conn, "INSTALL 'parquet.duckdb_extension';")
{:ok, _} = Duckdbex.query(conn, "LOAD 'parquet.duckdb_extension';")
```

## Error message
There are 2 **v**'s in the DuckDB version causing what looks like a version check to fail.

> Invalid Input Error: Extension \"parquet.duckdb_extension\" version (**v0.9.1**) does not match DuckDB version (**vv0.9.1**)
```
** (MatchError) no match of right hand side value: {:error, "Invalid Input Error: Extension \"parquet.duckdb_extension\" version (v0.9.1) does not match DuckDB version (vv0.9.1)"}
    (stdlib 5.1.1) erl_eval.erl:498: :erl_eval.expr/6
    #cell:oqbiodtkmzckg5pxjqqbx54hmbx3scm2:1: (file)
```

# Default installation
## Livebook code
Similar setup to above. Except
```
{:ok, _} = Duckdbex.query(conn, "INSTALL 'parquet';")
```

## Error message
There isn't a version **vv0.9.1** available from extensions.duckdb.org.

> HTTP Error: Failed to download extension "parquet" at URL "http://extensions.duckdb.org/vv0.9.1/linux_amd64/parquet.duckdb_extension.gz"
Extension "parquet" is an existing extension.

```
** (MatchError) no match of right hand side value: {:error, "HTTP Error: Failed to download extension \"parquet\" at URL \"http://extensions.duckdb.org/vv0.9.1/linux_amd64/parquet.duckdb_extension.gz\"\nExtension \"parquet\" is an existing extension.\n"}
    (stdlib 5.1.1) erl_eval.erl:498: :erl_eval.expr/6
    #cell:sotjunmtzt7gdddxbhho643be53rftzr:1: (file)
```

Thank you again for your effort creating this library. If I could identify the issue in the code to contribute more I would have.

**Comment by robert-baldwin** [comment]
Perhaps some environment information is helpful. I'm running Livebook via Docker by executing the command:
```docker run -p 8080:8080 -p 8081:8081 -v $(pwd):/data --pull always ghcr.io/livebook-dev/livebook```

It's being launched from a directory that includes the downloaded `parquet.duckdb_extension` for DuckDB version 9.1 for my CPU architecture.

**Comment by AlexR2D2** [comment]
Hi! It was the bug in the DuckDb source code
Created the new release of the of duckdbex with duckdb 0.9.2 bug fix release

**Comment by robert-baldwin** [comment]
Amazing, thank you!

**Comment by robert-baldwin** [comment]
Amazing, thank you!
