### ISSUE TITLE
Suport for column names in query results

### ISSUE THREAD

**Issue by mindreframer** [AlexR2D2/duckdbex#13]
Hi @AlexR2D2 , 

thank you for keeping duckdbex up-to-date, just got it working with 0.9.2. 

I've noticed, that there is currently no way to get column names for rows in the response, am I missing something? 
I think it limits the ability to automatically map responses to structs / maps. 
Is there any way to get hold of those column names?

**Comment by AlexR2D2** [comment]
HI @mindreframer,
Indeed, i missing the columns names. New build already in progress

```Elixir
    iex> {:ok, result_ref} = Duckdbex.query(conn, "SELECT col5, col2 from my_table;")
    iex> ["col5", "col2"] = Duckdbex.columns(result_ref)
```

**Comment by mindreframer** [comment]
Awesome! Thanks!
