### ISSUE TITLE
Upgrade to 0.10.0 

### ISSUE THREAD

**Issue by blackrez** [AlexR2D2/duckdbex#14]
Hello,

Thanks for this binding, did you plan to upgrade to the lastest version https://duckdb.org/2024/02/13/announcing-duckdb-0100.html ?

Also how it is hard to upgrade the code when a new duckdb is released ?

**Comment by AlexR2D2** [comment]
Hello, sure, i'll upgrade the duckdbex.
It is not hard, just pull duckdb, generate the duckdb.h and duckdb.cpp amalgamation files, copy files to the duckdbex, compile duckdbex and fix sometimes a NIF compile errors because of some changes in duckdb codebase (this is most hard part)

**Comment by nyo16** [comment]
I tried today to upgrade to v0.10.0 but i am getting an error `error: no type named 'PreservedError' in namespace 'duckdb'`
I did a grep to duckdb repo and it exists in 0.9.2 but not in 0.10. Sadly my c++ knowledge ends somewhere around here :)

**Comment by AlexR2D2** [comment]
Hello, 0.2.8 released with DuckDB 0.10.0
