### ISSUE TITLE
Action CI broken since {:duckdbex, "0.2.3"}

### ISSUE THREAD

**Issue by vgrechin** [AlexR2D2/duckdbex#15]
Fails to produce release assets for Linux, like duckdbex-nif-2.16-x86_64-linux-gnu-0.2.3.tar.gz

**Comment by willfore** [comment]
this should be resolved with pr #20

**Comment by vgrechin** [comment]
I'm closing the ticket, because starting from v0.3.2 the issue was fixed.

**Comment by AlexR2D2** [comment]
Thanks to willfore
