### ISSUE TITLE
Disconnect and Close?

### ISSUE THREAD

**Issue by willfore** [AlexR2D2/duckdbex#16]
While testing with querying a locally created database file I noticed there is no method to gracefully disconnect the connection and close the database. Was this by design? Am I missing a better way to do it? 

For reference the C documentation has both:

void duckdb_disconnect(
  duckdb_connection *connection
);

void duckdb_close(
  duckdb_database *database
);

Please let me know if I'm missing something here as that's a possibility ;)

**Comment by AlexR2D2** [comment]
The connection{database} must be closed automatically when you threw away the latest ref to the connection{database} resource. In this case ERTS call the destructor of connection object resource, this in turn will call the destructor of C++ DuckDB Connection{Database} objects, so you don't have to care about managing connection/database resources and leaks. This is why i integrated the [cpp version](https://duckdb.org/docs/api/cpp) of the DuckDB

```Elixir
{:ok, db} = Duckdbex.open() # db "variable" holds ref to database
{:ok, conn} = Duckdbex.connection(db) # conn holds ref to connection
db = nil # now there is no ref to database but conn still hods database internally 
conn = nil # now there are no references to the connection{database} and ERTS destroy connection resource and this will call destructors of Connection/Database DuckDB objects
```

**Comment by willfore** [comment]
Great! Thanks for the clarification.
