### ISSUE TITLE
List this library on DuckDB docs

### ISSUE THREAD

**Issue by nileshtrivedi** [AlexR2D2/duckdbex#18]
I think this library should be listed on this page: https://duckdb.org/docs/api/overview

**Comment by AlexR2D2** [comment]
Looks like it already listed
<img width="716" alt="Screenshot 2024-06-14 at 21 51 04" src="https://github.com/AlexR2D2/duckdbex/assets/31543570/4eb6c01e-7a3c-454f-af8c-4af9bc11c326">
