### ISSUE TITLE
Function to Destroy Prepared Statement

### ISSUE THREAD

**Issue by bhougland18** [AlexR2D2/duckdbex#22]
Hello,

Does this library have a function to destroy a prepared statement?  The DuckDB docs talk about this [method ](https://duckdb.org/docs/api/c/prepared.html) but I can't seem to find it.

oh, btw, thank you for creating this library, it is awesome!

**Comment by AlexR2D2** [comment]
Hello,

The Duckdbex uses not C but [C++ version](https://duckdb.org/docs/api/cpp#querying) of the DuckDB library.  When in your code the count of reference to the your prepared statement will be 0, the Erlang (ERTS) call [this function](https://github.com/AlexR2D2/duckdbex/blob/545e8522174be93ca9f0814ddb2637b4fc1c4e6c/c_src/nif.cpp#L529) for you. In the function the pointer to the PreparedStatement we be released and this in turn will call C++ PreparedStatement destructor automatically. So, just keep the reference to the any resource/DuckDB object (db, connection, result or  prepared statement) until you need and when just throw it away and 'resource/DuckDB object' will be destroyed automatically. This is for preventing you from the memory leaking (caused  by the Elixir code, not DuckDB itself code) if you forget to call some C special function to destroyt smth.

**Comment by bhougland18** [comment]
Supercool, thanks!
