### ISSUE TITLE
Add appender/3 that works with schemas 

### ISSUE THREAD

**Issue by tautQD** [AlexR2D2/duckdbex#23]
Currently trying to initialise an appender with "schema.table" appender/2 gives an error  
![Screenshot 2024-10-10 at 16 27 14](https://github.com/user-attachments/assets/c395c6b8-45a4-4d81-ad76-3cdbd5dccade)
Therefore it would be useful to have an appender/3 definition with conn, schema_name, table_name

**Comment by AlexR2D2** [comment]
Hi! Your PR is merged, thanks!
