### ISSUE TITLE
Using union types in appender

### ISSUE THREAD

**Issue by tautQD** [AlexR2D2/duckdbex#27]
Hello, I noticed that using union types with the appender throws an error (images). Is it a limitation of the appender API or is there a way to configure this so that it works? Thank you

![Screenshot 2024-10-29 at 17 16 05](https://github.com/user-attachments/assets/b374a200-8110-49b5-9c9f-b0c5c5ca47c9)
![Screenshot 2024-10-29 at 17 16 57](https://github.com/user-attachments/assets/ed84fe7c-d3a1-4bec-84fc-13a9d75b7c0b)

**Comment by AlexR2D2** [comment]
Hello, thanks, i am checking...

**Comment by AlexR2D2** [comment]
Hello, fixed in new release
