### ISSUE TITLE
Allow unsigned extension.

### ISSUE THREAD

**Issue by blackrez** [AlexR2D2/duckdbex#6]
Hello,

Is it possible to add the config parameter : `allow_unsigned_extensions` ?

**Comment by AlexR2D2** [comment]
Hello, I will try to add this parameter in the next update

**Comment by blackrez** [comment]
I don't if the release is ready to use but by reading the code I understand it's added.

**Comment by AlexR2D2** [comment]
> I don't if the release is ready to use but by reading the code I understand it's added.

just released

**Comment by blackrez** [comment]
Thanks I test it and it works.
